# Generated by Django 5.2.7 on 2025-10-18 07:43

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_forgetpasswordcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default.png",
                null=True,
                upload_to=users.models.avatar_upload_path,
            ),
        ),
    ]
